<a href="https://colab.research.google.com/github/DIKSHANTSHARMA1234/REINFOREMENT-LEARNING/blob/main/POLICY__AND__VALUE__ITERATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
states = [0,1,2,3,4]
action=[0,1]
N_STATES = len(states)
N_ACTIONS = len(action)



In [ ]:
print(N_STATES)

5


In [ ]:
print(N_ACTIONS)

2


In [ ]:
P = np.zeros((N_STATES,N_ACTIONS,N_STATES)) #TRANSITIONS PROBABLITY

In [ ]:
print(P)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
R = np.zeros((N_STATES,N_ACTIONS,N_STATES))  #REWARDS

In [ ]:
print(R)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
P[0,0,1] =1.0


In [ ]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]]]


In [ ]:

P[2,0,3] =1.0


In [ ]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
P[3,1,4] =1.0


In [ ]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
P[4,0,4] =1.0

In [ ]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
R[0,0,1]=1

In [ ]:
print(R)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
R[1,1,2]=10

In [ ]:
print(R)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
R[2,0,3]=100

In [ ]:
print(R)

[[[  0.   1.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0. 100.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]]


In [ ]:
R[3,1,4]=1000

In [ ]:
print(R)

[[[   0.    1.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.  100.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0. 1000.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]]


In [ ]:
R[4,0,4]=1.0

In [ ]:
print(R)

[[[   0.    1.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.  100.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0. 1000.]]

 [[   0.    0.    0.    0.    1.]
  [   0.    0.    0.    0.    0.]]]


In [ ]:
gamma = 0.75

In [ ]:
policy  = [0 for s in range (N_STATES)]
V = np.zeros(N_STATES)
print("INTIAL POLICY",policy)

INTIAL POLICY [0, 0, 0, 0, 0]


In [ ]:
is_value_changed =True
iterations = 0
while is_value_changed:
   is_value_changed = False
   iterations +=1
  ##run iteration for each state
   for s in range(N_STATES):
    V[s]=sum([P[s,policy[s],s1]*(R[s,policy[s],s1]+ gamma*V[s1]) for s1 in range (N_STATES)])
  

In [ ]:
for s in range (N_STATES):
  q_best = V[s]
  

In [ ]:
print(s)

4


In [ ]:
print(q_best)

1.0


In [ ]:
for a in range (N_ACTIONS):
  q_sa = sum([P[s,a,s1] * (R[s,a,s1] + gamma * V[s1]) for s1 in range (N_STATES)])
  if q_sa > q_best:
    print("State", s , ":q_sa", q_sa,"q_best", q_best)
    policy[s]=a
    q_best=q_sa
    is_value_changed=True
  

State 4 :q_sa 1.75 q_best 1.0


In [ ]:
print("Iteration:" , iterations)

Iteration: 1


In [ ]:
print(q_best)

1.75


In [ ]:
print(V)

[  1.   0. 100.   0.   1.]


In [ ]:
print(policy)

[0, 0, 0, 0, 0]
